name: Clean Repo

on:
  schedule:
    - cron: 00 19 * * 2
  workflow_dispatch:

jobs:
  clean-repo:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
    
      - name: Install Munki
        run: |
          curl -OL https://github.com/munki/munki/releases/download/v5.5.1/munkitools-5.5.1.4365.pkg
          sudo installer -pkg munkitools-5.5.1.4365.pkg -target /
          sudo rm munkitools-5.5.1.4365.pkg
      
      - name: Run makecatalogs
        run: |
          /usr/local/munki/makecatalogs $GITHUB_WORKSPACE/munki_repo
      
      - name: Run repoclean
        run: |
          /usr/local/munki/repoclean -a --keep 2 $GITHUB_WORKSPACE/munki_repo
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: clean-munki-repo
          commit-message: Remove old pkgs and pkgsinfo
          title: Remove old packages from Munki repo
          body: |
            This PR is automatically generated by Github Actions.