name: Update Recipe Trust

on:
  workflow_dispatch:
    inputs:
      recipe:
          description: 'Recipe override name'
          required: true

jobs:
  update-trust:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install AutoPkg
        run: |
          curl -OL https://github.com/autopkg/autopkg/releases/download/v2.3.1/autopkg-2.3.1.pkg
          sudo installer -pkg autopkg-2.3.1.pkg -target /
          sudo rm autopkg-2.3.1.pkg
       
      - name: Configure AutoPkg
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: | 
          defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "$GITHUB_WORKSPACE"/autopkg/RecipeOverrides/
          defaults write com.github.autopkg RECIPE_SEARCH_DIRS "$GITHUB_WORKSPACE"/autopkg/recipes/
          defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
          defaults write com.github.autopkg MUNKI_REPO "$GITHUB_WORKSPACE"/munki_repo
          defaults write com.github.autopkg GITHUB_TOKEN "$TOKEN"
            
      - name: Add AutoPkg Repos
        run: | 
          autopkg repo-add recipes

      
      # set-output truncates multi-line strings. So we need to do all this string substitution to circumvent that
      - name: Verify Trust Info and Save Output
        id: verify
        run: |
          echo "::set-output name=stdout::$(autopkg verify-trust-info -vv ${{ github.event.inputs.recipe }}.munki.recipe &> output.log)"
          export OUTPUT="$(cat output.log)"
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=verify-info::$(echo "$OUTPUT")"
        continue-on-error: true

      - name: Update Trust Info
        run: |
          autopkg update-trust-info ${{ github.event.inputs.recipe }}.munki.recipe
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-${{ github.event.inputs.recipe }}-trust-info
          title: Update recipe trust info for ${{ github.event.inputs.recipe }}
          commit-message: Update hashes
          body: |
            Output from `verify-trust-info`
            ```
            ${{ steps.verify.outputs.verify-info }}
            ```
            You should audit changes in the parent recipe yourself before merging.
            
            - This message is auto generated          